### ISSUE TITLE
Plugin fails to load after installation

### ISSUE THREAD

**Issue by johnsietsma** [VioletGiraffe/cppcheck-vs-addin#138] opened 2015-06-01 02:04 UTC
I installed the CppCheck plugin in Visual Studio 2013. And when opening a project I get a message box that says "The 'CPPCheckPluginPackage' did not load correctly.

The ActivityLog.xml files has the error message:
"Could not load file or assembly 'Microsoft.VisualStudio.Shell.11.0, Version=14.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified."

I imagine that it should be looking for VisualStudio.Shell.12.0.  Perhaps the assembly dependency is incorrect?

**Comment by VioletGiraffe** [comment] 2015-06-01 05:37
I get the same at home, where I don't have the VS SDK and only have VS 2013. I'll look into it tomorrow.

**Comment by Dmitry-Me** [comment] 2015-06-01 09:27
Dunno if that's related, but the project currently references `Microsoft.VisualStudio.Shell.X.0` with X being 8, 9, 10 and 11 but not 12. I would guess that adding such reference could magically solve the problem.

**Comment by VioletGiraffe** [comment] 2015-06-01 09:41
The better question is, when did it get broken.

**Comment by notoes** [comment] 2015-06-02 05:15
Well thanks for taking a look. It does sound like it needs the reference to
12. I'm happy to test a build for you if you like.

**Comment by VioletGiraffe** [comment] 2015-06-02 09:17
I've uploaded a new release, 1.3.1. Please give it a try: https://github.com/VioletGiraffe/cppcheck-vs-addin/releases/tag/1.3.1.0

**Comment by rob100** [comment] 2015-06-02 12:48
Hi,
I had the same problem, so I tried your new 1.3.1 release with no success. Then I tried to reproduce the problem in the debugger with your current master/head and the problem does not occurred. Is it possible, that the uploaded CppcheckPlugin.vsix from your link is not the newest one?

**Comment by VioletGiraffe** [comment] 2015-06-02 12:57
No, I've double-checked, it's the same.

**Comment by VioletGiraffe** [comment] 2015-06-02 13:02
The error message mentions `Microsoft.VisualStudio.Shell` reference, but there is no such reference in the module's assemblies. The only such extension available in the list is `Microsoft.VisualStudio.Shell.12.0`, there's no 11.0 or just universal `Shell` with no version number.

**Comment by VioletGiraffe** [comment] 2015-06-02 13:10
Try this VSIX: http://rghost.net/8XkG8wdqs
It should solve the problem, but break compatibility with VS 2013 and 2015.

**Comment by notoes** [comment] 2015-06-02 23:11
That works for me. I could install and use the add-in without any issues,

Thanks!

**Comment by VioletGiraffe** [comment] 2015-06-03 04:47
Okay, so that was it.

**Comment by manuelh** [comment] 2015-06-08 09:00
I'm experiencing the same issue with VS2013 and the latest version I got from here: https://github.com/VioletGiraffe/cppcheck-vs-addin/releases/tag/1.3.1.0

**Comment by bugparty** [comment] 2016-01-22 09:01
I am using Visual Studio 2012 update 5,
I also have this problem,the log is:
Could not load file or assembly 'Microsoft.VisualStudio.Shell.11.0, Version=14.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'

**Comment by VioletGiraffe** [comment] 2016-01-24 21:42
Works for me (VS 2013 Update 4)!

**Comment by thiessendg** [comment] 2016-03-24 12:40
I just downloaded this VS add-in and it's still not working. I have a fairly vanilla VS 2013 Update 5 installed. Is there any way to get this to work?

Here is the relevant material from G:\Users\dthiessen\AppData\Roaming\Microsoft\VisualStudio\12.0\ActivityLog.xml

<entry>
    <record>909</record>
    <time>2016/03/24 12:29:38.526</time>
    <type>Warning</type>
    <source>VisualStudio</source>
    <description>Unexpected system error mode before loading package [CPPCheckPluginPackage]</description>
    <guid>{127D8BD3-8CD7-491A-9A63-9B4E89118DA9}</guid>
  </entry>
  <entry>
    <record>910</record>
    <time>2016/03/24 12:29:38.526</time>
    <type>Information</type>
    <source>VisualStudio</source>
    <description>Begin package load [CPPCheckPluginPackage]</description>
    <guid>{127D8BD3-8CD7-491A-9A63-9B4E89118DA9}</guid>
  </entry>
  <entry>
    <record>911</record>
    <time>2016/03/24 12:29:38.557</time>
    <type>Error</type>
    <source>VisualStudio</source>
    <description>CreateInstance failed for package [CPPCheckPluginPackage]</description>
    <guid>{127D8BD3-8CD7-491A-9A63-9B4E89118DA9}</guid>
    <hr>80070002</hr>
    <errorinfo>Could not load file or assembly 'Microsoft.VisualStudio.Shell.11.0, Version=14.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.</errorinfo>
  </entry>
  <entry>
    <record>912</record>
    <time>2016/03/24 12:29:38.557</time>
    <type>Error</type>
    <source>VisualStudio</source>
    <description>End package load [CPPCheckPluginPackage]</description>
    <guid>{127D8BD3-8CD7-491A-9A63-9B4E89118DA9}</guid>
    <hr>80004005 - E_FAIL</hr>
    <errorinfo>Could not load file or assembly 'Microsoft.VisualStudio.Shell.11.0, Version=14.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.</errorinfo>
  </entry>
</activity>

**Comment by VioletGiraffe** [comment] 2016-03-24 13:26
Sorry, guys, my mistake. I was wondering how come **bugparty**'s fix didn't solve the problem for you (as it was supposed to), and then I realized I actually never released a fixed plugin! So please install the latest release, it should work fine: https://github.com/VioletGiraffe/cppcheck-vs-addin/releases/latest

**Comment by thiessendg** [comment] 2016-03-24 13:54
Still doesn't work. Won't load. Here is the newest snip from the xml...

 <entry>
    <record>643</record>
    <time>2016/03/24 13:52:32.462</time>
    <type>Information</type>
    <source>VisualStudio</source>
    <description>Begin package load [CPPCheckPluginPackage]</description>
    <guid>{127D8BD3-8CD7-491A-9A63-9B4E89118DA9}</guid>
  </entry>
  <entry>
    <record>644</record>
    <time>2016/03/24 13:52:32.477</time>
    <type>Error</type>
    <source>VisualStudio</source>
    <description>CreateInstance failed for package [CPPCheckPluginPackage]</description>
    <guid>{127D8BD3-8CD7-491A-9A63-9B4E89118DA9}</guid>
    <hr>80070002</hr>
    <errorinfo>Could not load file or assembly 'Microsoft.VisualStudio.Shell.11.0, Version=14.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.</errorinfo>
  </entry>
  <entry>
    <record>645</record>
    <time>2016/03/24 13:52:32.477</time>
    <type>Error</type>
    <source>VisualStudio</source>
    <description>End package load [CPPCheckPluginPackage]</description>
    <guid>{127D8BD3-8CD7-491A-9A63-9B4E89118DA9}</guid>
    <hr>80004005 - E_FAIL</hr>
    <errorinfo>Could not load file or assembly 'Microsoft.VisualStudio.Shell.11.0, Version=14.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.</errorinfo>
  </entry>

**Comment by thiessendg** [comment] 2016-03-24 13:57
![capture](https://cloud.githubusercontent.com/assets/18050738/14018969/689f2484-f19e-11e5-831a-140af060841b.PNG)

**Comment by VioletGiraffe** [comment] 2016-03-24 14:01
I assume that's with the new version?

**Comment by thiessendg** [comment] 2016-03-24 14:02
Yes, newest version, still doesn't load.

**Comment by thiessendg** [comment] 2016-03-24 14:04
Seems like it is assuming I have VS 2012, not VS 2013 or 2015 from the Could not load file or assembly 'Microsoft.VisualStudio.Shell.11.0 lines in the xml... shrug...

**Comment by VioletGiraffe** [comment] 2016-03-24 14:07
Could be that the 11.0 version is hardcoded, when it shouldn't be. But the problem is that it works on both my PCs no problem with VS 2013 and 2015.

**Comment by thiessendg** [comment] 2016-03-24 14:40
That's weird.  I have VS 2015 on another machine, let me get to that and try it there.

**Comment by thiessendg** [comment] 2016-03-24 14:52
OK, weird... works fine on Win 10 / VS 2015... So, something is haywire with my Win 7 / VS 2013 platform... I will see what I can find.  Thanks!

**Comment by VioletGiraffe** [comment] 2016-03-24 18:46
Note: this is a duplicate of #138

**Comment by thiessendg** [comment] 2016-03-24 19:13
I tried everything I could think of, including a "Repair" of VS 2013 and nothing worked. I finally said to heck with it and downloaded the zip from GitHub and "rebuilt" the plugin. The rebuilt plugin now works. No idea why that worked.

**Comment by VioletGiraffe** [comment] 2016-03-24 19:15
I have no doubt the problem is with the add-in rather than with VS.

**Comment by bugparty** [comment] 2016-03-25 02:33
the latest source has patched by me ,maybe you haven`t download the latest
build

**Comment by VioletGiraffe** [comment] 2016-03-25 08:26
I did `git pull` before building the release.

**Comment by calexiev** [comment] 2016-05-18 13:51
Hello!
I had the same problem with the lates version on 64 bits. Could you please indicate the general solution?

**Comment by VioletGiraffe** [comment] 2017-09-19 07:16
Closing as too old - much has changed in the add-in's settings since then (for one, VS 2013 is probably no longer supported).

**Closed by VioletGiraffe** 2017-09-19 07:16 UTC
Labels: bug
