### ISSUE TITLE
selected row unreadable in analysis result window (dark theme)

### ISSUE THREAD

**Issue by jmlundberg** [VioletGiraffe/cppcheck-vs-addin#174] opened 2017-10-11 17:18 UTC
Image attached
![darkthemeinvisible](https://user-images.githubusercontent.com/2904748/31455743-e1e74d7a-aeb8-11e7-940c-39b82971cd03.png)

**Comment by VioletGiraffe** [comment] 2017-10-11 18:33
Duplicate of #152. I did not find a way to fix this, although clearly there is a way.

**Closed by VioletGiraffe** 2017-10-11 18:33 UTC
