### ISSUE TITLE
Please release a 2017-preview compatible version

### ISSUE THREAD

**Issue by janwilmans** [VioletGiraffe/cppcheck-vs-addin#167] opened 2017-09-04 23:32 UTC
tried to install 1.3.3 -> does not support vs2017 yet. 
I do see commits to fix this, but was unable to build the sources in vs2017 :) 

After fixing the references and re-targetting to .net platform 4.6.2, I ended up with 

C:\Program Files (x86)\Microsoft Visual Studio\Preview\Community\MSBuild\Microsoft\VisualStudio\v15.0\VSSDK\Microsoft.VsSDK.targets(99,5): error VSSDK1078: The VSIX manifest must contain element 'Prerequisites'. For more information, https://go.microsoft.com/fwlink/?linkid=839777
========== Build: 0 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========

I realized its a vs2015 project, so someone, pretty please  build a new release for us 2017 people :)

**Comment by VioletGiraffe** [comment] 2017-09-05 05:09
Odd, I thought I fixed this. Perhaps, I forgot to commit something, will check when I get to the office where I have the latest version. It does build in 2017 and install into 2017 for me. 

Problem is, the plugin is currently unusable in 2017 because of #156

**Comment by janwilmans** [comment] 2017-09-05 07:52
Ok, thanks for the swift response. In the coming three weeks I'm very busy, but if the projects builds/installs in vs2017 and the problem persists when I'm back I'm willing to look into it myself, I'll check back in a while

**Comment by VioletGiraffe** [comment] 2017-09-05 07:54
Gotcha. Maybe I'll finally get around to fixing it myself. I more or less know how to do it, but it's tedious.

**Comment by VioletGiraffe** [comment] 2017-09-12 12:36
Weird, but I am building the revision from master with and for VS 2017 no problem. I don't know why it doesn't work for you.

**Comment by janwilmans** [comment] 2017-09-12 14:02
Maybe I did something wrong, or it might be a vs2017 preview specific problem (i'm using the preview edition). I will re-test.

**Comment by VioletGiraffe** [comment] 2017-09-12 15:19
I'm using the latest final update.

**Comment by janwilmans** [comment] 2017-09-12 19:25
I see, well, I get this:
1>------ Build started: Project: CPPCheckPlugin, Configuration: Debug Any CPU ------
1>C:\Program Files (x86)\Microsoft Visual Studio\Preview\Community\MSBuild\15.0\Bin\Microsoft.Common.CurrentVersion.targets(1987,5): warning MSB3275: The primary reference "Microsoft.VisualStudio.Shell.Immutable.10.0" could not be resolved because it has an indirect dependency on the assembly "Microsoft.VisualStudio.Utilities, Version=15.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a" which was built against the ".NETFramework,Version=v4.6" framework. This is a higher version than the currently targeted framework ".NETFramework,Version=v4.5".
1>C:\Program Files (x86)\Microsoft Visual Studio\Preview\Community\MSBuild\15.0\Bin\Microsoft.Common.CurrentVersion.targets(1987,5): warning MSB3275: The primary reference "Microsoft.VisualStudio.Shell.Immutable.11.0" could not be resolved because it has an indirect dependency on the assembly "Microsoft.VisualStudio.Utilities, Version=15.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a" which was built against the ".NETFramework,Version=v4.6" framework. This is a higher version than the currently targeted framework ".NETFramework,Version=v4.5".
1>C:\Program Files (x86)\Microsoft Visual Studio\Preview\Community\MSBuild\15.0\Bin\Microsoft.Common.CurrentVersion.targets(1987,5): warning MSB3245: Could not resolve this reference. Could not locate the assembly "Microsoft.VisualStudio.Shell.11.0". Check to make sure the assembly exists on disk. If this reference is required by your code, you may get compilation errors.
1>C:\Program Files (x86)\Microsoft Visual Studio\Preview\Community\MSBuild\15.0\Bin\Microsoft.Common.CurrentVersion.targets(1987,5): warning MSB3245: Could not resolve this reference. Could not locate the assembly "Microsoft.VisualStudio.VCProjectEngine, Version=12.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a". Check to make sure the assembly exists on disk. If this reference is required by your code, you may get compilation errors.
1>C:\Program Files (x86)\Microsoft Visual Studio\Preview\Community\MSBuild\15.0\Bin\Microsoft.Common.CurrentVersion.targets(2604,5): warning MSB3283: Cannot find wrapper assembly for type library "Microsoft.VisualStudio.CommandBars". Verify that (1) the COM component is registered correctly and (2) your target platform is the same as the bitness of the COM component. For example, if the COM component is 32-bit, your target platform must not be 64-bit.
========== Build: 0 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========


Which (i believe) means that although it can be build in vs2017, it relies on vs2015 being installed.

**Comment by VioletGiraffe** [comment] 2017-09-12 19:33
I _think_ the project targets VS 2015 SDK, so you need to have that SDK installed.

**Comment by Altrue** [comment] 2017-09-13 20:47
Here is what solved it for me (Windows 7, Visual Studio 2017) : in source.extension.vsixmanifest, add a Prerequisite to "Visual Studio core editor". The version range for me that was automatically filled was [15.0.26606.0,16.0)

**Comment by VioletGiraffe** [comment] 2017-09-13 20:52
@Altrue : can you please change the lower version of that prerequisite from 15 to 14 or 13 (the lowest that won't cause build issues), and make a pull request?

**Comment by Altrue** [comment] 2017-09-13 21:41
I actually don't think that it worked :(

I did build and install properly, but once I try to scan anything it never reports any error or does anything. And my projects apparently aren't "C++ projects" somehow.

I'm using the GUI version separately for my projects for now.

**Comment by VioletGiraffe** [comment] 2017-09-13 22:06
@Altrue 
#156

**Comment by VioletGiraffe** [comment] 2017-09-18 20:17
Closing as the original issue had been sorted, and the other one is already open.

**Comment by VioletGiraffe** [comment] 2017-09-18 21:25
@Altrue  @janwilmans 
I have released the new version of the plugin that should work with VS 2017 (it works for me). Please try it out.

**Comment by mloskot** [comment] 2017-09-18 23:51
@VioletGiraffe I've installed successfully with the latest VS2017 (Release, not Preview).

It works with small solution with single project (`.vcxproj` manually created using the VS2017), with single .cpp file.

If I try to use it with large solution with number of projects (all `.vcxproj` manually created using the VS2017), then I'm getting an error:

![vs-cppcheck-addin](https://user-images.githubusercontent.com/80741/30569717-b15bf4c8-9cdc-11e7-873d-70735f44941a.png)

The same error happens for not-so-big solution with projects generated with CMake 3.9.

Right-click in Solution Explorer on individual files  or projects as well makes no difference and the same error occurs. VS restarts do not help.

**Comment by VioletGiraffe** [comment] 2017-09-19 04:56
That does not occur with two of my largest solutions, one containing 5 projects and the other - 28. I will try it out on another PC, but if I won't get this error, someone else will have to debug it.

**Comment by mloskot** [comment] 2017-09-19 12:39
@VioletGiraffe 
I have tested it on another Windows 10 machine and also with latest VS2017 (15.3.4).

* If I load single `.vcxproj` into VS, the add-in works and analyses the project.
and it seems to work there.

* If I add another `.vcxproj` to the same solution as loaded above, it still works.

* If I load large (+200 `.vcxproj`) solution, it no longer works. It throws the error about "Object reference..." as above or this one, randomly:
![cppcheck-addin-with-vs2017-no-valid-config](https://user-images.githubusercontent.com/80741/30592524-615a01d4-9d47-11e7-828b-3f3d4bbfddf1.png)
I confirmed all projects have the same Configuration/Platform selected.

* Then, I start removing projects one by one and at some point, after re-loading smaller solution, the add-in starts working again.

I know this is probably of little help, but perhaps it will ring a bell.

I'm not able to debug the thing now.

I also tried the latest w/ VS2012, see #171

**Comment by VioletGiraffe** [comment] 2017-09-19 12:58
Thanks for the info. I'll try to find a test solution that would trigger this behavior. Do you know of a suitable open-source project?

**Comment by mloskot** [comment] 2017-09-19 13:32
> Do you know of a suitable open-source project?

My favourite among giants is `.sln` with ~450 `.vcxproj` one can generate with CMake to build LLVM/clang.

**Comment by VioletGiraffe** [comment] 2017-09-19 13:34
That sounds like fun...
At least I have an SSD and a decent 8-core CPU, I should be able to open it if I let it do its thing for the whole evening, right? :)

**Comment by mloskot** [comment] 2017-09-19 13:36
LLVM without clang and cmake-configured without some optional modules should make it less :)

**Comment by Dmitry-Me** [comment] 2017-09-19 14:04
Would it be possible to reproduce the problem by creating an empty solution and then adding newly created "Win32 console application" projects into it?

**Comment by VioletGiraffe** [comment] 2017-09-19 14:09
@Dmitry-Me: good idea!

**Comment by VioletGiraffe** [comment] 2017-09-19 20:13
So it's the same problem I came across yesterday when debugging #156: reflection doesn't work, quite literally. And I don't understand why. In that case it was the function `isCppProject`, this time it's `isCppFile`.

**Comment by mloskot** [comment] 2017-09-19 20:27
Any chance this bug reported for VS2017 is related [VCProject.Configurations property broken for multiple C++ projects](https://developercommunity.visualstudio.com/content/problem/12260/vcprojectconfigurations-property-broken-for-multip.html)

It is about property of `Microsoft.VisualStudio.VCProjectEngine.VCProject` interface.

**Comment by VioletGiraffe** [comment] 2017-09-19 20:29
@mloskot 
I have not gotten the configuration error message yet so I can't say. Have been debugging "Object reference not set to an instance".

**Comment by janwilmans** [comment] 2017-09-19 21:29
I was able to install 1.3.4 on visual studio preview, but on this project:
https://github.com/CobaltFusion/DebugViewPP

I get:
---------------------------
Microsoft Visual Studio
---------------------------
Object reference not set to an instance of an object.
---------------------------
OK   
---------------------------

So I hope thats a reproduction scenario for you?

**Comment by janwilmans** [comment] 2017-09-19 22:37
I was able to build the head in vs2017, and attached the debugger:
![image](https://user-images.githubusercontent.com/5933444/30618695-ddb8683e-9d9b-11e7-8e5b-b46d06cf59d4.png)

**Comment by VioletGiraffe** [comment] 2017-09-20 05:03
@janwilmans 
The problem is with reflection. A valid `VCFile` instance is obtained in CPPCheckPluginPackage.cs:538. I can get `file.Type` there no problem. But after I pass this `file` to `isCppFile` as `dynamic`, I cannot obtain its `Type` through reflection. And I don't understand why.

**Comment by janwilmans** [comment] 2017-09-20 07:03
but the getinterface of vcfile is already returning nullptr, right

**Comment by VioletGiraffe** [comment] 2017-09-20 07:33
@janwilmans: right, and I don't quite understand what this code even does (luckily, I'm not its author, he-he). The way I see it, `isCppFile ` should be doing the following:

```
var fileObjectType = file.GetType();
var fileType = fileObjectType.GetProperty("FileType").GetValue(file);
```

But it doesn't work either.

**Closed** 2020-08-09 19:05 UTC
