### ISSUE TITLE
CPPCheckPluginPackage did not load correctly: VS2013

### ISSUE THREAD

**Issue by wwarriner** [VioletGiraffe/cppcheck-vs-addin#142] opened 2015-07-01 05:48 UTC
The following error occurs while trying to load the plugin following installation:
![untitled](https://cloud.githubusercontent.com/assets/6930772/8448314/78909c50-1f8b-11e5-830e-18cb9d3747e7.PNG)

In the activity log is:

```
  <entry>
    <record>853</record>
    <time>2015/07/01 05:36:11.686</time>
    <type>Error</type>
    <source>VisualStudio</source>
    <description>End package load [CPPCheckPluginPackage]</description>
    <guid>{127D8BD3-8CD7-491A-9A63-9B4E89118DA9}</guid>
    <hr>80004005 - E_FAIL</hr>
    <errorinfo>Could not load file or assembly 'Microsoft.VisualStudio.Shell.11.0, Version=14.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.</errorinfo>
  </entry>
```

Where I noted the use of `*.Shell.11.0`

Going into the extension folder and changing the following entry in "extension.vsixmanifest"

```
<Dependency Id="Microsoft.VisualStudio.MPF.11.0" DisplayName="Visual Studio MPF 11.0" Version="11.0" />
```

manually to replace 11.0 with 12.0 causes the plugin to work fine.

After downloading and poking around the project, and around the internet, I've discovered what I believe to be related to the issue:
Using CTRL+SHIFT+F, and searching for "11.0" yields

```
Find all "11.0", Subfolders, Find Results 1, "Entire Solution ( Including External Items )", "*.cs;*.resx;*.resw;*.xsd;*.wsdl;*.xaml;*.xml;*.htm;*.html;*.css"
  ~\cppcheck-vs-addin-master\CPPCheckPlugin\CPPCheckPluginPackage.cs(17):    [DefaultRegistryRoot(@"Software\Microsoft\VisualStudio\11.0")]
  ~\cppcheck-vs-addin-master\CPPCheckPlugin\Properties\Settings.Designer.cs(16):    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "11.0.0.0")]
  Matching lines: 2    Matching files: 2    Total files searched: 29
```

Replacing those instances of 11.0 with 12.0, building, and installing the build also resolves the issue for me.

I don't know nearly enough about C# or the VS SDK, but I also found: [github.com](https://github.com/jfromaniello/nestin/issues/2) and [stackoverflow.com](http://stackoverflow.com/questions/25606632/how-can-a-vs-extension-target-multiple-versions-in-regard-to-microsoft-visualstu/25629018#25629018) which may be relevant to fixing the issue in a robust fashion.

**Comment by VioletGiraffe** [comment] 2015-07-01 06:41
I believe this edit (replacing 11.0 with 12.0) will break VS 2012 support. Other than that, I don't understand _anything_ here.

**Comment by Dmitry-Me** [comment] 2015-07-02 08:58
How about using a range for "version" as in this change https://github.com/mkurdej/cppcheck-vs-addin/commit/38c36a690dd1bfb5df7bbb033b3af9c6e990249e ?

**Comment by VioletGiraffe** [comment] 2015-07-02 10:27
As long as it works, feel free to edit everything :)

**Comment by SanderBouwhuis** [comment] 2015-08-26 09:23
I'm having this problem as well.
Does anyone have an update where this is fixed? (I don't have C# and never created a plugin)

@VioletGiraffe 
What do you mean with "I've lost all ability to work on this project"?

**Comment by VioletGiraffe** [comment] 2015-08-26 18:39
@SanderBouwhuis : getting a build error, see #141

**Comment by FelixBer** [comment] 2015-09-06 16:48
I just hit this error after upgrading from version 1.2.1 to 1.3.1.

The error occurs with 1.3 and 1.3.1, but not with 1.2.1. Reverting to 1.2.1 for now.

**Comment by VioletGiraffe** [comment] 2015-09-06 19:01
@FelixBer: it's fixed already, just need someone to rebuild the .vsix because I can't.

**Comment by SanderBouwhuis** [comment] 2015-09-08 08:55
@FelixBer
So, if I use v1.2.1 it will work with VS2013?

**Comment by francispauli** [comment] 2015-09-11 19:43
i had the same error as <b>warriner</b>  in VS2013 but got up and running with  v1.2.1

**Comment by altumano** [comment] 2015-09-24 10:38
So, the latest release 1.3.1.0 is still not working with Visual Studio 2013.
Is there any plan to release a fix?

**Comment by VioletGiraffe** [comment] 2015-09-24 10:49
I'd be happy to, as soon as someone helps me solve the problem with building the project.

**Comment by VioletGiraffe** [comment] 2015-09-24 10:50
@altumano : I'd be happy to, as soon as someone helps me solve the problem with building the project.

**Comment by FelixBer** [comment] 2015-09-25 08:24
I can build it at work later but my release build is only half the size of previous releases. Were you uploading debug builds or am I missing something in the build process?

**Comment by VioletGiraffe** [comment] 2015-09-25 09:24
@FelixBer : There's nothing to miss. I don't think I'd upload a debug build, but it's not impossible.
It'd be great if I could build the project myself, too...

**Comment by SanderBouwhuis** [comment] 2015-09-25 12:15
Yay for FelixBer.

**Comment by FelixBer** [comment] 2015-09-25 13:06
Here we go:

built from 486b1593cb4318f9d23f7e7a159373caf377a656
tested with cppcheck 1.69 x86

http://rghost.net/6HmGcFFZc

I only tested it very briefly by scanning some projects with cppcheck 1.69 x86 and Visual Studio 2013.

Would be great if someone else could test it too.

**Comment by VioletGiraffe** [comment] 2015-09-25 13:13
I see you didn't increment the version number. That's bad because then you can't update without uninstalling the extension first.

**Comment by FelixBer** [comment] 2015-09-25 13:53
Fixed. I built from a clean checkout and forgot to bump the version number. I can only send you a pull req for it later though.

**Comment by SanderBouwhuis** [comment] 2015-09-27 06:44
@FelixBer 
Unfortunately, it doesn't seem to work. The installation proceeds correctly, but in VS2013 I don't have any CppCheck menu items.

**Comment by FelixBer** [comment] 2015-09-27 11:53
That's odd. Did you restart VS? Try going to tools->updates and extensions and uninstall it if its there. Then close down all VS instances and install it again. Then start VS.


I just tried it again in various constellations and settings and it works for me.


Two questions: Does anything show up in tools->updates and extensions? Does it work with version 1.3.1, the latest official release?

I'll only have time to look at this next week.

**Comment by SanderBouwhuis** [comment] 2015-09-28 09:33
CppCheck is in Tools/Extensions and updates.

Just to make sure, should there be a new menu for CppCheck in the UI where I can change some settings? Because I don't have that.

**Comment by FelixBer** [comment] 2015-09-28 11:29
No, there should bee two menu items under the "Tools" menu. 

Tools -> check current project with cppcheck
Tools -> cppcheck settings

**Comment by SanderBouwhuis** [comment] 2015-09-28 12:47
Aaaaah, shoot! Ok, in that case, it works.

Mea culpa.

**Comment by adm1961** [comment] 2015-10-01 15:08
I've just installed the current version into VS2013 and although the menu entries are there, when clicked they don't do anything. I can run cppcheck fine from the command line though. Any ideas?

**Comment by adm1961** [comment] 2015-10-01 15:09
I did have to use nuget to get the shell.11 file though - is it worth changing the shell version to 12 as detailed above or shouldn't that be needed?

**Comment by FelixBer** [comment] 2015-10-01 15:52
Make sure cppcheck 1.69 x86 is installed. You should also get an error message, either a messagebox or in the output pane or the cppcheck panel.

**Comment by VioletGiraffe** [comment] 2015-10-01 16:24
`C:\Program Files\Cppcheck\cppcheck.exe has exited with code -1073741515` 
Don't know what's wrong. Can't debug because of #141.

**Comment by wwarriner** [comment] 2015-10-01 21:48
The same (or similar) is now happening in VS2015, and the change may be more complex. I haven't figured out totally how to fix it, and may not figure it out. There may be changes to dependency structure.

**Comment by SanderBouwhuis** [comment] 2015-10-02 06:07
Maybe we can ask someone from Microsoft?

**Comment by VioletGiraffe** [comment] 2015-10-02 07:04
We can ask on MSDN forums (https://social.msdn.microsoft.com/Forums/en-US/home?forum=vsx).

**Comment by willll** [comment] 2015-11-17 18:12
I have the same issue with VS2012 premium and the latest release 1.3.1.0 : 

    Could not load file or assembly 'Microsoft.VisualStudio.Shell.11.0, Version=14.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified

**Comment by VioletGiraffe** [comment] 2015-11-18 10:46
Try this one: https://drive.google.com/file/d/0B8Qc2atC6FVKc1RMb25XbkJENFk/view?usp=sharing

**Comment by VioletGiraffe** [comment] 2015-11-22 19:10
Try the new release, this issue _should_ be fixed there.

**Comment by BrunoMartinGym** [comment] 2016-01-22 15:58
I also tried to install the 1.3.2 release on VS2013 with update 5 and I get the same error message (albeith in French!):
```
Impossible de charger le fichier ou l'assembly 'Microsoft.VisualStudio.Shell.11.0, Version=14.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' ou une de ses dépendances. Le fichier spécifié est introuvable.
```

Here are extracts of my VS2013 Activity log (showing the error) and plugin installation log (which worked correctly).  Hope this can help solve the problem because I would really like to try CppCheck in VS! 


[ActivityLog.txt](https://github.com/VioletGiraffe/cppcheck-vs-addin/files/101053/ActivityLog.txt)

[VSIXInstaller_11ef023d-50cd-457d-bde4-c48caa35c716.txt](https://github.com/VioletGiraffe/cppcheck-vs-addin/files/101042/VSIXInstaller_11ef023d-50cd-457d-bde4-c48caa35c716.txt)

**Comment by VioletGiraffe** [comment] 2016-01-24 21:32
It worked fine for me on a fresh machine just a month ago, both on VS2015 and 2013.

**Comment by BrunoMartinGym** [comment] 2016-01-25 14:02
Hello,
Here is the info about my Visual Studio 2013 installation.  I have the Update 5 installed as well as many third parties plugin (Qt, Image Watch, NVidia stuff, AQtime, Visual Assist, Visual Hg).  Are any of them known to interact badly with your plugin?

```
Microsoft Visual Studio Community 2013
Version 12.0.40629.00 Update 5
Microsoft .NET Framework
Version 4.5.51209

Installed Version: Professional

Team Explorer for Visual Studio 2013   06177-004-0444002-02970
Microsoft Team Explorer for Visual Studio 2013

Visual Basic 2013   06177-004-0444002-02970
Microsoft Visual Basic 2013

Visual C# 2013   06177-004-0444002-02970
Microsoft Visual C# 2013

Visual C++ 2013   06177-004-0444002-02970
Microsoft Visual C++ 2013

Visual F# 2013   06177-004-0444002-02970
Microsoft Visual F# 2013

Visual Studio 2013 Code Analysis Spell Checker   06177-004-0444002-02970
Microsoft® Visual Studio® 2013 Code Analysis Spell Checker

Portions of International CorrectSpell™ spelling correction system © 1993 by Lernout & Hauspie Speech Products N.V. All rights reserved.

The American Heritage® Dictionary of the English Language, Third Edition Copyright © 1992 Houghton Mifflin Company. Electronic version licensed from Lernout & Hauspie Speech Products N.V. All rights reserved.

Application Insights Tools for Visual Studio Package   1.0
Application Insights Tools for Visual Studio

ASP.NET and Web Tools   12.5.60612.0
Microsoft Web Developer Tools contains the following components:
Support for creating and opening ASP.NET web projects
Browser Link: A communication channel between Visual Studio and browsers
Editor extensions for HTML, CSS, and JavaScript
Page Inspector: Inspection tool for ASP.NET web projects
Scaffolding: A framework for building and running code generators
Server Explorer extensions for Microsoft Azure Web Apps
Web publishing: Extensions for publishing ASP.NET web projects to hosting providers, on-premises servers, or Microsoft Azure

ASP.NET Web Frameworks and Tools 2012.2   4.1.21001.0
For additional information, visit http://go.microsoft.com/fwlink/?LinkID=309563

ASP.NET Web Frameworks and Tools 2013   5.2.30612.0
For additional information, visit http://www.asp.net/

Common Azure Tools   1.4
Provides common services for use by Azure Mobile Services and Microsoft Azure Tools.

CPPCheckPlugin   1.2.0
cppcheck wrapper

Image Watch   1.0

Microsoft Azure Mobile Services Tools   1.4
Microsoft Azure Mobile Services Tools

NuGet Package Manager   2.8.60610.756
NuGet Package Manager in Visual Studio. For more information about NuGet, visit http://docs.nuget.org/.

NVIDIA CUDA 6.5 Wizards   6.5
Wizards to create new NVIDIA CUDA projects and source files.

NVIDIA Nsight   4.1
NVIDIA Nsight Visual Studio Edition provides tools for GPGPU and graphics development.  Copyright © NVIDIA 2013.
·Direct3D® and DirectX® are registered trademarks of Microsoft Corporation in the United States and/or other countries.
·Microsoft Detours is used under the Professional license (http://research.microsoft.com/en-us/projects/detours/).
·Gardens Point Parser Generator Copyright 2005 Queensland University of Technology (QUT). All rights reserved.
·NLog Copyright © 2004-2006 Jaroslaw Kowalski <jaak@jkowalski.net>
·IronPython and WPFToolkit used under Microsoft Public License (Ms-PL) and are Copyright © Microsoft Corporation
·Portions of RadControls for WPF © 2010-2011 by Telerik Corporation.  All rights reserved.
·zlib and libpng used under the zlib/libpnc license (http://opensource.org/licenses/Zlib) 

Warning: This computer program is protected by copyright law and international treaties. Unauthorized reproduction or distribution of this program, or any portion of it, may result in severe civil and criminal penalties, and will be prosecuted to the maximum extent possible under the law.

PreEmptive Analytics Visualizer   1.2
Microsoft Visual Studio extension to visualize aggregated summaries from the PreEmptive Analytics product.

PVS-Studio   5.23.11894.2
PVS-Studio is a static code analyzer for C/C++ (Microsoft Visual Studio) with a simple licensing and pricing policies which is easy to install and use without a need to deploy complex maintenance environment.

SmartBear AQtime    
SmartBear AQtime Pro for Visual Studio. Version: 8.41.1556.7

SQL Server Data Tools   12.0.41012.0
Microsoft SQL Server Data Tools

Visual Assist   
For more information about Visual Assist, see the Whole Tomato Software website at http://www.WholeTomato.com. Copyright (c) 1997-2015 Whole Tomato Software, Inc.

VisualHG   1.1.6
Mercurial source contol provider.

Windows Phone 8.1 SDK Integration   1.0
This package integrates the tools for the Windows Phone 8.1 SDK into the menus and controls of Visual Studio.

Qt Add-in 1.2.4
This is Visual Studio Add-in component for Qt. For more information about Qt, see 
http://qt.digia.com
Copyright (C) 2012 Digia Plc and/or its subsidiary(-ies)
```

**Comment by VioletGiraffe** [comment] 2016-01-25 18:51
@BrunoMartinGym : I have no such knowledge.

**Comment by Vitaliy-Grigoriev** [comment] 2016-01-25 22:43
@BrunoMartinGym : I also have Visual Assist plug-in and I have the bug with incorrect loading CPPCheckPluginPackage. Possible, Visual Assist causes this error.

**Comment by VioletGiraffe** [comment] 2016-01-26 05:43
@Vitaliy-Grigoriev : I have Visual Assist and no bugs.

**Comment by bugparty** [comment] 2016-01-27 05:14
@BrunoMartinGym  @willll try my release http://rghost.net/75VTbBNgg

**Comment by BrunoMartinGym** [comment] 2016-01-27 19:50
Hello Bugparty,

Thanks for the patch.  I uninstalled the CppCheck I had and installed your release.  I no longer get the error while starting VS and the analysis works!

Regards!

**Comment by VioletGiraffe** [comment] 2016-01-27 20:01
Great, thanks for the conformation. I will update the release tomorrow, if I don't forget to.

**Comment by fjautard** [comment] 2016-02-17 10:27
Dear All,

Thank for this very promising add-in.
I'm new in this forum. 
I installed cppcheck 1.72 and the plugin in VS213 SP4. I loaded one C++ project, clicked on "TOOLS/Check current project with cppcheck": cppcheck analysis completed and the Cppcheck analysis results window is displayed.
But this window is totally empty, even if the standalone cppcheck finds some issues in this project.

What is wrong ?
Please help me.
TIA
FrancoisJ from France

**Comment by oskarwaglund** [comment] 2016-02-19 09:54
@fjautard, @VioletGiraffe  
Hi,

I am having the exact same problem. Downloaded the add-in from http://rghost.net/75VTbBNgg and then the 32-bit version of 1.72. When I run the analysis in VS13 the results window is completely empty although there should be a million issues due to the code being old and badly maintained. 

If I run the GUI application on my SRC folder with 87 files I get zero issues as well. It says that it has analyzed 87 files during 9 seconds but the actual time spent is only a fraction of a second. I thought it was because the files were open in Visual Studio, but it still doesn't work after closing it.

Any thoughts on this?

Best regards!

**Comment by VioletGiraffe** [comment] 2016-02-19 10:00
@fjautard @oskarwaglund  I have similar problem on both home and office PC after the latest cppcheck update. So far I don't understand what the problem is.

**Comment by fjautard** [comment] 2016-02-19 11:28
@VioletGiraffe, @oskarwaglund
Thanks for your reply.
I redo the same on a freshly installed Windows 10 machine. I installed VS2015 redistributable files.
Everything is already.
I will investigate on my Win7 PC and send feedbacks (vcredist issue !?).

**Comment by oskarwaglund** [comment] 2016-02-19 12:52
@fjautard, @VioletGiraffe
I tried copying my source files to a folder on ../desktop and running the GUI tool on that folder. All of a sudden it works! It seems that something in my project/solution is preventing the tool from reading the files or something. I tried some older versions as well and they behave in the same way. 

It's not a solution to the problem but perhaps it can help you figure out what's wrong? 

//Oskar

**Comment by GrenMeera** [comment] 2016-03-18 14:13
@VioletGiraffe 
This is not working for several developers I know using VS2012 Premium and is the same output as described by @willll earlier using the latest release.

However, @bugparty 's release at http://rghost.net/75VTbBNgg seems to clear it right up.

At one point in my testing of different installations, I had to clear my extension cache out of the Visual Studio AppData folder on Windows 7 in order to get different results.  I thought I'd add that detail to the discussion.

**Comment by VioletGiraffe** [comment] 2016-03-24 13:29
@GrenMeera: the new 1.3.3 release fixes this error.

**Comment by GrenMeera** [comment] 2016-03-24 18:26
@VioletGiraffe I just uninstalled the plugin, cleared my %Appdata Extension cache, restarted a fresh Visual Studio 2012, then closed it again so that I had a fully clean %Appdata Extension cache.

I then ran the 1.3.3 Release installer.  The bug is still present in Visual Studio 2012 on this release.

If I go through this entire process with bugparty's release, the error message is gone.

**Comment by VioletGiraffe** [comment] 2016-03-24 18:44
That suggests @bugparty didn't commit some of the important changes, IMO.

**Comment by bugparty** [comment] 2016-03-25 02:36
oh, I am sure I have commit all the changes,maybe the compiler maters?I am
using visual studio 2012,so maybe the guys who are using visual studio 2012
could use my build

**Comment by VioletGiraffe** [comment] 2016-03-25 08:26
No idea... I used VS2015 to build the release.

**Comment by bugparty** [comment] 2016-03-25 09:03
I have both VS2015 and VS2012,I will build two relase later, Maybe We can
find some reasons

**Comment by GrenMeera** [comment] 2016-03-25 12:44
@VioletGiraffe @bugparty Let me know if you need an additional testing bench as I have been able to reproduce this consistently.

**Comment by lohengrin** [comment] 2016-04-12 12:34
Since I have this problem for a long time, I was using the  @bugparty 's release without problem.
I Just installed the new 1.3.3 version and it does not solved this issue (same error message as before)
Going back to  @bugparty 's release works fine.
Using Visual Studio 2013 Update 5.

**Comment by bugparty** [comment] 2016-04-15 10:28
I checkout the latest master source code and build with vs2012 and 2015
build with vs2012
http://rghost.net/6DPj2MMYh
build with vs2015
http://rghost.net/7xBctbtwz

**Comment by VioletGiraffe** [comment] 2016-04-15 10:36
@bugparty 
The latest release is built from the current master source. If your builds do work for people who have this issue, I suppose we'd have to look into your project settings or IDE settings that aren't in the repository.

**Comment by bugparty** [comment] 2016-04-15 11:17
it works for my vs2012 and vs2013,but I don`t have any settings different
from others

**Comment by lohengrin** [comment] 2016-04-15 12:05
Yes, @bugparty version VS2012 and VS2015 works fine on my VS2013 Update 5 (the official version does not work).
The Extensions and Updates manager still display version 1.3.1 version (and not 1.3.3) with both. Is it normal ?

**Comment by VioletGiraffe** [comment] 2016-04-15 12:09
@bugparty  @lohengrin 
No, that's not normal. The source code in the report is 1.3.3: https://github.com/VioletGiraffe/cppcheck-vs-addin/blob/master/CPPCheckPlugin/source.extension.vsixmanifest

It means that you didn't build the latest source. It might also mean there are some uncommited changes on bugparty's PC that fix this issue.

**Comment by bugparty** [comment] 2016-04-15 16:21
but I just clone a new copy on the master and build it

**Comment by VioletGiraffe** [comment] 2016-04-15 16:32
But you can see that my link is correct, and the manifest says 1.3.3, right? Then how come your builds are 1.3.1?

**Comment by bugparty** [comment] 2016-04-15 19:42
sorry,I will double check it

**Comment by GrenMeera** [comment] 2016-04-15 21:51
@bugparty 
Both of your builds made in 2012 and 2015 work with my 2012 Professional.

I am also getting the same results as @lohengrin and my builds are listed as version 1.3.1 in my Extension manager.

Also oddly enough the plugins are listed as version 1.2.0 if you go to Help->About Microsoft Visual Studio

**Comment by VioletGiraffe** [comment] 2016-04-16 04:30
@GrenMeera 
Yes, it does show 1.2.0 in About - clearly, that number is coming from a different place, possibly from the source code. That's not a concern in the context of this issue. 
I have just double-checked that the latest release does indeed show up as 1.3.3 in "Extensions and updates".

**Comment by christheenchanter** [comment] 2016-09-16 14:52
Visual studio 2013 update 5 version# 12.0.40629.00. windows 10 pro 64-bit.
[ActivityLog.txt](https://github.com/VioletGiraffe/cppcheck-vs-addin/files/477091/ActivityLog.txt)

**Comment by T-Jin** [comment] 2016-09-19 23:27
Finally got it working! 

I had exact same problem with @christheenchanter.
I'm only using VS2013 update 5 #12.0.40629.00 with win7 64-bit. 

Clone the repo and build it on my machine solved the problem.

**Comment by VioletGiraffe** [comment] 2016-09-20 06:49
@T-Jin : could you attach your VSIX here so that other people with the same problem can try it out? I wonder if it only works when built on the same machine where it'll be used or not.

**Comment by LinuxdevelopersOrg** [comment] 2016-09-20 08:56
The one built by @bugparty on Mar 18 works on my machine with only VS2013. The official one does not. The official one did work in VS2013 when I had VS2015 installed, though (uninstalled it yesterday, and cppcheck stopped working).

**Comment by VioletGiraffe** [comment] 2016-09-20 09:02
What about this one?
[CppcheckPlugin.zip](https://github.com/VioletGiraffe/cppcheck-vs-addin/files/482037/CppcheckPlugin.zip)

**Comment by LinuxdevelopersOrg** [comment] 2016-09-20 09:17
@VioletGiraffe Sorry, did not work for me. I cloned and rebuilt this one, and this one works on my machine(tm) (after a rudimentary check-on-save quick test).

[CppcheckPlugin.zip](https://github.com/VioletGiraffe/cppcheck-vs-addin/files/482072/CppcheckPlugin.zip)

**Comment by T-Jin** [comment] 2016-09-21 17:34
@VioletGiraffe Here is my release build. It worked on my  win7 64-bit with only VS2013 installed.
[CppcheckPlugin.zip](https://github.com/VioletGiraffe/cppcheck-vs-addin/files/485656/CppcheckPlugin.zip)

**Comment by MikelLuri** [comment] 2016-10-04 06:37
My cppcheckplugin didn't work. I've tried with the build by @T-Jin and now it works. I also have win7 x64 and only VS2013 installed.

**Comment by andrei-dragusanu** [comment] 2017-01-10 16:08
On Visual Studio 2012/Windows 7 64bit it is also not working (realease 1.3.3):
![image](https://cloud.githubusercontent.com/assets/17052614/21813551/56020d94-d75f-11e6-82bb-d0aa3a47ab41.png)
```  
<entry>
    <record>450</record>
    <time>2017/01/10 16:03:52.004</time>
    <type>Information</type>
    <source>VisualStudio</source>
    <description>Begin package load [CPPCheckPluginPackage]</description>
    <guid>{127D8BD3-8CD7-491A-9A63-9B4E89118DA9}</guid>
  </entry>
  <entry>
    <record>451</record>
    <time>2017/01/10 16:03:52.016</time>
    <type>Error</type>
    <source>VisualStudio</source>
    <description>CreateInstance failed for package [CPPCheckPluginPackage]</description>
    <guid>{127D8BD3-8CD7-491A-9A63-9B4E89118DA9}</guid>
    <hr>80070002</hr>
    <errorinfo>Could not load file or assembly 'Microsoft.VisualStudio.Shell.11.0, Version=14.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.</errorinfo>
  </entry>
  <entry>
    <record>452</record>
    <time>2017/01/10 16:03:52.016</time>
    <type>Error</type>
    <source>VisualStudio</source>
    <description>End package load [CPPCheckPluginPackage]</description>
    <guid>{127D8BD3-8CD7-491A-9A63-9B4E89118DA9}</guid>
    <hr>80004005 - E_FAIL</hr>
    <errorinfo>Could not load file or assembly 'Microsoft.VisualStudio.Shell.11.0, Version=14.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.</errorinfo>
  </entry>

**Comment by VioletGiraffe** [comment] 2019-06-30 07:34
VS 2013 is no longer supported. If you get this error on a newer version of Visual Studio with the latest release, open a new issue.

**Closed by VioletGiraffe** 2019-06-30 07:34 UTC
Labels: bug
